#pragma once
#include "common/type/type_def.hpp"

namespace Nano
{
    enum class RawInputType
    {
        _None,
        _Down,
        _Release,
        _Move
    };

    enum class CustomInputType
    {
        _Down,
        _Release,
        _Click,
        _Press,
        _Move
    };

    enum class InputDeviceType : uint8_t
    {
        _Mouse = 1,
        _Keyboard,
        _Gamepad
    };

    enum class InputKey : uint32_t
    {
        _None = 0,
        _MouseButton0 = (static_cast<uint32_t>(InputDeviceType::_Mouse) << 24) + 0,
        _MouseButtonLeft = _MouseButton0,
        _MouseButton1,
        _MouseButton_Middle = _MouseButton1,
        _MouseButton2,
        _MouseButtonRight = _MouseButton2,
        _MouseButton3,
        _MouseButtonWheelUp = _MouseButton3,
        _MouseButton4,
        _MouseButtonWheelDown = _MouseButton4,
        _MouseButton5,
        _MouseButton6,
        _MouseButton7,
        _MouseButton8,
        _MouseAxisX,
        _MouseAxisY,
        _MouseAxisXY,
        _MouseButtonCount = _MouseAxisXY - _MouseButton0 + 1,

        _KeyEscape = (static_cast<uint32_t>(InputDeviceType::_Keyboard) << 24) + 0,
        _KeyF1,
        _KeyF2,
        _KeyF3,
        _KeyF4,
        _KeyF5,
        _KeyF6,
        _KeyF7,
        _KeyF8,
        _KeyF9,
        _KeyF10,
        _KeyF11,
        _KeyF12,
        _KeyF13,
        _KeyF14,
        _KeyF15,
        _KeyF16,
        _KeyF17,
        _KeyF18,
        _KeyF19,
        _KeyPrint,
        _KeyScrollLock,
        _KeyBreak,

        _KeySpace,

        _KeyApostrophe,
        _KeyComma,
        _Key_Minus,
        _KeyPeriod,
        _KeySlash,

        _Key0,
        _Key1,
        _Key2,
        _Key3,
        _Key4,
        _Key5,
        _Key6,
        _Key7,
        _Key8,
        _Key9,

        _KeySemicolon,
        _KeyLess,
        _KeyEqual,

        _KeyA,
        _KeyB,
        _KeyC,
        _KeyD,
        _KeyE,
        _KeyF,
        _KeyG,
        _KeyH,
        _KeyI,
        _KeyJ,
        _Key_K,
        _KeyL,
        _Key_M,
        _KeyN,
        _KeyO,
        _KeyP,
        _KeyQ,
        _KeyR,
        _KeyS,
        _KeyT,
        _KeyU,
        _KeyV,
        _KeyW,
        _KeyX,
        _KeyY,
        _KeyZ,

        _KeyBracketLeft,
        _KeyBackslash,
        _KeyBracketRight,

        _KeyGrave,

        _KeyLeft,
        _KeyRight,
        _KeyUp,
        _KeyDown,
        _KeyInsert,
        _KeyHome,
        _KeyDelete,
        _KeyEnd,
        _KeyPageUp,
        _KeyPageDown,

        _KeyNumLock,
        _Key_KpEqual,
        _Key_KpDivide,
        _Key_Kp_Multiply,
        _Key_KpSubtract,
        _Key_KpAdd,
        _Key_KpEnter,
        _Key_KpInsert,
        _Key_KpEnd,
        _Key_KpDown,
        _Key_KpPageDown,
        _Key_KpLeft,
        _Key_KpBegin,
        _Key_KpRight,
        _Key_KpHome,
        _Key_KpUp,
        _Key_KpPageUp,
        _Key_KpDelete,

        _KeyBackSpace,
        _KeyTab,
        _KeyReturn,
        _KeyCapsLock,
        _KeyShiftL,
        _KeyCtrlL,
        _KeySuperL,
        _KeyAltL,
        _KeyAltR,
        _KeySuperR,
        _Key_Menu,
        _KeyCtrlR,
        _KeyShiftR,

        _KeyBack,
        _KeySoftLeft,
        _KeySoftRight,
        _KeyCall,
        _KeyEndcall,
        _KeyStar,
        _KeyPound,
        _KeyDpadCenter,
        _KeyVolumeUp,
        _KeyVolumeDown,
        _KeyPower,
        _KeyCamera,
        _KeyClear,
        _KeySymbol,
        _KeyExplorer,
        _KeyEnvelope,
        _KeyEquals,
        _KeyAt,
        _KeyHeadsethook,
        _KeyFocus,
        _KeyPlus,
        _KeyNotification,
        _KeySearch,
        _Key_MediaPlayPause,
        _Key_MediaStop,
        _Key_MediaNext,
        _Key_MediaPrevious,
        _Key_MediaRewind,
        _Key_MediaFastForward,
        _Key_Mute,
        _KeyPictsymbols,
        _KeySwitchCharset,

        _KeyForward,
        _KeyExtra1,
        _KeyExtra2,
        _KeyExtra3,
        _KeyExtra4,
        _KeyExtra5,
        _KeyExtra6,
        _KeyFn,

        _KeyCircumflex,
        _KeySsharp,
        _KeyAcute,
        _KeyAltGr,
        _KeyNumbersign,
        _KeyUdiaeresis,
        _KeyAdiaeresis,
        _KeyOdiaeresis,
        _KeySection,
        _KeyAring,
        _KeyDiaeresis,
        _KeyTwosuperior,
        _KeyRightParenthesis,
        _KeyDollar,
        _KeyUgrave,
        _KeyAsterisk,
        _KeyColon,
        _KeyExclam,

        _KeyBraceLeft,
        _KeyBraceRight,
        _KeySysRq,

        _KeyCount = _KeyEscape - _KeySysRq + 1,


        _PadButtonLeftStickX = (static_cast<uint32_t>(InputDeviceType::_Gamepad) << 24) + 0,
        _PadButtonLeftStickY,
        _PadButtonRightStickX,
        _PadButtonRightStickY,
        _PadButtonAxis4,
        _PadButtonAxis5,
        _PadButtonAxis6,
        _PadButtonAxis7,
        _PadButtonAxis8,
        _PadButtonAxis9,
        _PadButtonAxis10,
        _PadButtonAxis11,
        _PadButtonAxis12,
        _PadButtonAxis13,
        _PadButtonAxis14,
        _PadButtonAxis15,
        _PadButtonAxis16,
        _PadButtonAxis17,
        _PadButtonAxis18,
        _PadButtonAxis19,
        _PadButtonAxis20,
        _PadButtonAxis21,
        _PadButtonAxis22,
        _PadButtonAxis23,
        _PadButtonAxis24,
        _PadButtonAxis25,
        _PadButtonAxis26,
        _PadButtonAxis27,
        _PadButtonAxis28,
        _PadButtonAxis29,
        _PadButtonAxis30,
        _PadButtonAxis31,
        _PadButtonAccelerationX,
        _PadButtonAccelerationY,
        _PadButtonAccelerationZ,
        _PadButtonGravityX,
        _PadButtonGravityY,
        _PadButtonGravityZ,
        _PadButtonGyroscopeX,
        _PadButtonGyroscopeY,
        _PadButtonGyroscopeZ,
        _PadButtonMagneticFieldX,
        _PadButtonMagneticFieldY,
        _PadButtonMagneticFieldZ,
        _PadButtonStart,
        _PadButtonSelect,
        _PadButtonLeft,
        _PadButtonRight,
        _PadButtonUp,
        _PadButtonDown,
        _PadButtonA,
        _PadButtonB,
        _PadButtonX,
        _PadButtonY,
        _PadButtonL1,
        _PadButtonR1,
        _PadButtonL2,
        _PadButtonR2,
        _PadButtonL3,
        _PadButtonR3,
        _PadButtonHome,
        _PadButton17,
        _PadButton18,
        _PadButton19,
        _PadButton20,
        _PadButton21,
        _PadButton22,
        _PadButton23,
        _PadButton24,
        _PadButton25,
        _PadButton26,
        _PadButton27,
        _PadButton28,
        _PadButton29,
        _PadButton30,
        _PadButton31,
        _PadButtonCount = _PadButton31 - _PadButtonLeftStickX
    };
}